### ISSUE TITLE
Critical Error caused by no End of Poll date set in drafted poll

### ISSUE THREAD

**Issue by bwiebeck** [andremacola/acf-onyx-poll#11]
I got an automated email from wordpress with the following error information

  An error of type E_ERROR was caused in line 131 of the file /wp-content/plugins/acf-onyx-poll/admin/poll-type.php. Error message: Uncaught Error: Call to a member function format() on bool in /wp-content/plugins/acf-onyx-poll/admin/poll-type.php:131
    Stack trace:
    #0 /wp-includes/class-wp-hook.php(287): OnyxPollsCpt->custom_columns('end', 42604)
    #1 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
    #2 /wp-includes/plugin.php(478): WP_Hook->do_action(Array)
    #3 /wp-admin/includes/class-wp-posts-list-table.php(1271): do_action('manage_onyxpoll...', 'end', 42604)
    #4 /wp-admin/includes/class-wp-list-table.php(1410): WP_Posts_List_Table->column_default(Object(WP_Post), 'end')
    #5 /wp-admin/includes/class-wp-posts-list-table.php(1304): WP_List_Table->single_row_columns(Object(WP_Post))
    #6 /wp-admin/includes/class-wp-posts-list-table.php(751): WP_Posts_List_Table->single_row(Object(WP_Post), 0)

After a bit of investigating, it seems like it was caused by a drafted poll that didnt have an end date set. The admin page was trying to grab a date, format it, then echo it. So it could also be when it tries to format a null value.

 $date = get_field('onyx_poll_end', $post_id);
 $date = DateTime::createFromFormat('Y-m-d H:i:s', $date);
 $date = $date->format('d/m/Y');
 echo "$date";

**Comment by andremacola** [comment]
End date should be always required by ACF. But I include a conditional for this column.

Thank you for the issue. This will be fixed in the next release.
