### ISSUE TITLE
Save location of ACF JSON files is changed without user consent

### ISSUE THREAD

**Issue by rampantprint** [andremacola/acf-onyx-poll#12]
On initialization the save location for ACF JSON is changed without user knowledge. This is problematic for various reasons, but it's especially destructive for users and developers that already use the default location ([https://www.advancedcustomfields.com/resources/local-json/](https://www.advancedcustomfields.com/resources/local-json/)) and frequently update field groups. I discovered the issue when changes to fields groups were not being reflected and contents of my acf-json folder was not being updated. This type of configuration should be an option and transparent to the user.

https://github.com/andremacola/acf-onyx-poll/blob/36de99e6d81a1e84a517f10d47e33b1caa3c28f3/onyx-poll.php#L89

**Comment by andremacola** [comment]
I thought I already removed that. It was a version for internal use.

Will fix in the next release.
